const Employee = [
  {
    id: 6,
    email: "employee6@example.com",
    password: "1234",
    tasks: [
      {
        taskTitle: "Submit monthly report",
        taskDescription: "Compile and submit the monthly performance report.",
        taskDate: "2025-06-05",
        category: "Reporting",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Client follow-up",
        taskDescription: "Call clients to follow up on pending feedback.",
        taskDate: "2025-06-07",
        category: "Communication",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Database cleanup",
        taskDescription: "Remove outdated records from the system.",
        taskDate: "2025-05-29",
        category: "Maintenance",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 7,
    email: "employee7@example.com",
    password: "1234",
    tasks: [
      {
        taskTitle: "Team meeting prep",
        taskDescription: "Prepare slides for the team sync-up meeting.",
        taskDate: "2025-06-08",
        category: "Planning",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Design mockup",
        taskDescription: "Create a mockup for the new landing page.",
        taskDate: "2025-06-03",
        category: "Design",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Resolve support tickets",
        taskDescription: "Address at least 10 open support tickets.",
        taskDate: "2025-06-02",
        category: "Support",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Document API changes",
        taskDescription: "Update documentation to reflect new API endpoints.",
        taskDate: "2025-06-04",
        category: "Documentation",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 8,
    email: "employee8@example.com",
    password: "1234",
    tasks: [
      {
        taskTitle: "Security audit",
        taskDescription: "Check server security and report issues.",
        taskDate: "2025-06-01",
        category: "Security",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Create test cases",
        taskDescription: "Write unit tests for the payment module.",
        taskDate: "2025-06-06",
        category: "Testing",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Code review",
        taskDescription: "Review pull requests from junior devs.",
        taskDate: "2025-06-05",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 9,
    email: "employee9@example.com",
    password: "1234",
    tasks: [
      {
        taskTitle: "Marketing campaign",
        taskDescription: "Plan and launch email marketing campaign.",
        taskDate: "2025-06-10",
        category: "Marketing",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Schedule interviews",
        taskDescription: "Arrange interviews for frontend developer position.",
        taskDate: "2025-06-07",
        category: "HR",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Social media update",
        taskDescription: "Post company news on LinkedIn and Twitter.",
        taskDate: "2025-06-02",
        category: "Social Media",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Quarterly goals review",
        taskDescription: "Analyze and document Q2 goals progress.",
        taskDate: "2025-06-05",
        category: "Management",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 10,
    email: "employee10@example.com",
    password: "1234",
    tasks: [
      {
        taskTitle: "Internal training",
        taskDescription: "Attend internal session on cloud infrastructure.",
        taskDate: "2025-06-06",
        category: "Training",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "DevOps deployment",
        taskDescription: "Deploy new app version to staging.",
        taskDate: "2025-06-07",
        category: "DevOps",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Bug fixing",
        taskDescription: "Fix bugs reported in the last sprint.",
        taskDate: "2025-06-03",
        category: "Development",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Write blog post",
        taskDescription: "Draft a technical blog on new features.",
        taskDate: "2025-06-08",
        category: "Content",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
];

const Admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "1234",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("Employee", JSON.stringify(Employee));
  localStorage.setItem("admin", JSON.stringify(Admin));
};

export const getLocalStorage = () => {
  const Employee = JSON.parse(localStorage.getItem("Employee"));
  const Admin = JSON.parse(localStorage.getItem("admin"));
  return { Employee, Admin };
};
